# Generated by Django 4.1.2 on 2022-10-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='verification_required',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
