# Generated by Django 4.0.2 on 2022-10-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='total_views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.IntegerField(default=0)),
            ],
        ),
    ]
