# Generated by Django 4.1.2 on 2022-11-10 04:38

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_fees_amount_event_payment_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='payment_required',
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=events.models.eventImageUploadPath),
        ),
    ]
