# Generated by Django 4.1.2 on 2022-11-10 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image_required',
        ),
    ]
