# Generated by Django 4.1.2 on 2022-11-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_event_image_remove_event_image_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='hits',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
