# Generated by Django 4.1.2 on 2022-11-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_visit_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='order',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
