# Generated by Django 4.1.2 on 2022-11-15 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_delete_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fees_per_member',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='eventusertable',
            name='amount_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='amount_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='is_thapar_team',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='max_count',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='events.event')),
            ],
        ),
    ]
