# Generated by Django 4.1.2 on 2022-11-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_event_fees_per_member_eventusertable_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='curr_female_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='curr_male_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='max_female_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='max_male_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='prize1',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='prize2',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='Prize',
        ),
    ]
