# Generated by Django 4.1.2 on 2022-11-16 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_event_rules_array'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='rules_array',
        ),
    ]
