# Generated by Django 4.1.2 on 2022-11-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_remove_event_rules_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reg_redirect_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
