# Generated by Django 4.1.2 on 2022-11-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_event_reg_redirect_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='thapar_auditions_done',
            field=models.BooleanField(default=False),
        ),
    ]
