# Generated by Django 4.1.2 on 2022-11-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_event_thapar_auditions_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventusertable',
            name='paid_amount_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventusertable',
            name='screenshot_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='paid_amount_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='screenshot_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
