# Generated by Django 4.1.2 on 2022-10-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('phone_no', models.CharField(max_length=15)),
                ('is_thaparian', models.BooleanField(blank=True, default=False)),
                ('roll_no', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('id_proof', models.URLField(blank=True, default=None, max_length=5000, null=True)),
                ('college', models.CharField(blank=True, default=None, max_length=350, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, default=None, max_length=7, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
