# Generated by Django 4.1.2 on 2022-10-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_proof_url',
            field=models.URLField(blank=True, default=None, max_length=600, null=True),
        ),
    ]
