# Generated by Django 4.1.2 on 2022-10-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_user_id_proof_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_proof_url',
            field=models.URLField(blank=True, default=None, max_length=5000, null=True),
        ),
    ]
