# Generated by Django 4.1.2 on 2022-10-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_alter_user_id_proof_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, default=None, max_length=7, null=True),
        ),
    ]
