# Generated by Django 4.0.2 on 2022-11-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_unverifieduser_remove_user_is_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnverifiedUser',
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
