# Generated by Django 4.1.2 on 2022-11-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_delete_unverifieduser_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnverifiedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('phone_no', models.CharField(max_length=15)),
                ('gender', models.CharField(default=None, max_length=20, null=True)),
                ('is_thaparian', models.BooleanField(blank=True, default=False)),
                ('roll_no', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('id_proof', models.URLField(blank=True, default=None, max_length=5000, null=True)),
                ('college', models.CharField(blank=True, default=None, max_length=350, null=True)),
                ('slug', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
