# Generated by Django 4.1.2 on 2022-11-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_alter_user_gender_alter_user_phone_no_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
