# Generated by Django 4.1.2 on 2022-11-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_delete_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unverifieduser',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='unverifieduser',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
