# Generated by Django 4.1.2 on 2022-11-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_remove_unverifieduser_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unverifieduser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
