# Generated by Django 4.1.2 on 2022-11-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0010_unverifieduser_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
    ]
