# Generated by Django 4.1.2 on 2022-11-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0011_pendingemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingemail',
            name='event',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='pendingemail',
            name='fees_per_member',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pendingemail',
            name='fees_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pendingemail',
            name='individual_fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pendingemail',
            name='is_create_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pendingemail',
            name='is_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pendingemail',
            name='is_join_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pendingemail',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pendingemail',
            name='members_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pendingemail',
            name='qr_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pendingemail',
            name='team_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pendingemail',
            name='team_key',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pendingemail',
            name='team_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='pendingemail',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
