# Generated by Django 4.1.2 on 2022-11-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0013_pendingemail_main_vrf_skip'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingemail',
            name='ignore_message',
            field=models.BooleanField(default=False),
        ),
    ]
