# Generated by Django 4.1.2 on 2022-11-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_verifyendpoint_url_alter_verifyendpoint_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
